##异常

&emsp;&emsp;当一个程序是由一些相互分离的模块组成时，特别是当这些模块来自某些独立开发的库时，错误处理的工作就需要分成两个相互独立的部分：

    1)、一方报告出那些无法在局部解决的错误。
    2)、另一方处理那些在其他地方检查出的错误。

一个库的作者可以检查出运行时的错误，但一般说，他对于应该如何去做就没有什么主意了。库的使用者可能知道如何去处理某些错误，但却无法去检查它们---不要然用户就会在自己的代码里处理这些错误，而不会把它们留给库。

&emsp;&emsp;在计算器的例子里我们回避了这个问题，因为那里设计的是一个程序整体。在这样做时，我们就可能将错误处理问题放在整个程序的框架中考虑。但是，当我们将计算器程序的各个逻辑部分分开，放进各自的名字空间之后，我们就看到每个名字空间都要依赖于名字空间Error（8.2.2节），而Error里的错误处理又要依赖于各模块在错误出现后的恰当行为。